In [1]:
# Imports

# Core
from pathlib import Path

# Science
import numpy as np
import hdbscan

# Plotting
import seaborn as sns


# Crystalography
import mdc3
from mdc3.types.datasets import MultiCrystalDataset
from mdc3.types.real_space import (MCDXMap,
                                   xmap_to_numpy_cartesian_axis,
                                   xmap_from_dataset,
                                   xmap_to_numpy_crystalographic_axis,
                                   )
from mdc3.functions.alignment import align_datasets
from mdc3.types import base



In [2]:
# Arguments
data_dirs = "/dls/science/groups/i04-1/conor_dev/dataset_clustering/redone/MUREECA"

In [3]:
# Load datasets
dataset = MultiCrystalDataset.mcd_from_pandda_input_dir(Path(data_dirs),
                                                       pdb_regex="*_final.pdb",
                                                       mtz_regex="*_final.mtz",
                                                       )
dataset.datasets

{'MUREECA-x0083': <mdc3.types.datasets.Dataset at 0x7f95181bbc18>,
 'MUREECA-x0051': <mdc3.types.datasets.Dataset at 0x7f95181bbcc0>,
 'MUREECA-x0053': <mdc3.types.datasets.Dataset at 0x7f94b6c19a58>,
 'MUREECA-x0054': <mdc3.types.datasets.Dataset at 0x7f94b5f8c780>,
 'MUREECA-x0059': <mdc3.types.datasets.Dataset at 0x7f94b55ee240>,
 'MUREECA-x0060': <mdc3.types.datasets.Dataset at 0x7f94b4b75c50>,
 'MUREECA-x0061': <mdc3.types.datasets.Dataset at 0x7f94b3ef45c0>,
 'MUREECA-x0062': <mdc3.types.datasets.Dataset at 0x7f94b3419ac8>,
 'MUREECA-x0063': <mdc3.types.datasets.Dataset at 0x7f94b2969780>,
 'MUREECA-x0064': <mdc3.types.datasets.Dataset at 0x7f94b1ea17f0>,
 'MUREECA-x0065': <mdc3.types.datasets.Dataset at 0x7f94b139e550>,
 'MUREECA-x0066': <mdc3.types.datasets.Dataset at 0x7f94b08dd908>,
 'MUREECA-x0067': <mdc3.types.datasets.Dataset at 0x7f94afebf438>,
 'MUREECA-x0070': <mdc3.types.datasets.Dataset at 0x7f94af45b9b0>,
 'MUREECA-x0075': <mdc3.types.datasets.Dataset at 0x7f94ae9ed9

In [4]:
# Hashmap
datasets = base.HashMap(dataset.datasets)

In [5]:
# Filter datasets with different numbers of CAs
first_dataset_key = list(datasets._dictionary.keys())[-1]
reference_dataset = datasets[first_dataset_key]
# def get_number_cas(d):
#     return len([atom for atom in d.structure.structure.get_atoms() if atom.name == "CA"])
# def get_number_res(d):
#     ress = []
#     for res in d.structure.structure.get_residues():
#         print(res.get_id())
#         try:
#             ca = res["CA"]
#             print(ca.get_full_id())
#             ress.append(res)
#         except:
#             pass
        
#     return ress
    
# reference_dataset_num_cas = get_number_cas(reference_dataset)
# print(reference_dataset_num_cas)
# # reference_dataset_num_cas
# for dtag, d in datasets._dictionary.items():
#     print(dtag, get_number_cas(dataset), get_number_res(d))
    

In [6]:
# Align pdbs
aligned_datasets = datasets.bind(lambda d: align_datasets(reference_dataset, d))

	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.2691726   0.9630892   0.00230269]
 [ 0.96307519  0.26915304  0.00654359]
 [ 0.00568229  0.00397902 -0.99997594]], [-66.67825523  50.90465386 -26.52199919]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.29011653  0.95695857 -0.00791756]
 [ 0.95691453  0.29018813  0.01026752]
 [ 0.01212317 -0.00459765 -0.99991594]], [-67.52926493  50.21817913 -27.06066329]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-2.72706410e-01  9.62097290e-01  1.33039407e-04]
 [ 9.62092972e-01  2.72704766e-01  3.03721699e-03]
 [ 2.88581776e-03  9.56264822e-04 -9.99995379e-01]], [-66.60067461  50.65967547 -26.43050389]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26891689  0.96316193  0.00167322]
 [ 0.96315061  0.26890397  0.00561715]
 [ 0.00496029  0.00312211 -0.99998282]], [-66.76344612  51.02543101 -26.56022223]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-2

	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-2.71892536e-01  9.62327439e-01  5.89978375e-04]
 [ 9.62322548e-01  2.71889061e-01  3.41352905e-03]
 [ 3.12452400e-03  1.49586256e-03 -9.99994000e-01]], [-66.32741007  50.4633542  -26.38255326]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-2.63125273e-01  9.64761374e-01  7.63355457e-04]
 [ 9.64730939e-01  2.63110491e-01  8.19056940e-03]
 [ 7.70109816e-03  2.89157843e-03 -9.99966165e-01]], [-66.56222466  50.99143897 -26.64085896]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[ 0.99719396 -0.07436238  0.00862756]
 [ 0.07437566  0.99722954 -0.00122879]
 [-0.00851228  0.00186702  0.99996203]], [-53.23505509  -3.23501577 -25.49551073]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-2.65446245e-01  9.64125254e-01 -8.86067635e-04]
 [ 9.64089621e-01  2.65444156e-01  8.40250695e-03]
 [ 8.33627063e-03  1.37616531e-03 -9.99964306e-01]], [-66.53071092  50.93065407 -26.742438

	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.27615017  0.96107929 -0.00822679]
 [ 0.96090042  0.2762592   0.01874137]
 [ 0.02028467 -0.00272969 -0.99979052]], [-66.88413658  50.80912609 -26.76466881]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[ 0.99824953 -0.05505785  0.02159887]
 [ 0.05490902  0.99846376  0.00742451]
 [-0.02197447 -0.00622554  0.99973915]], [-52.70173668  -4.21665327 -25.88022233]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26779926  0.9634594  -0.00543588]
 [ 0.96316065  0.26785175  0.02402095]
 [ 0.02459922  0.00119717 -0.99969668]], [-66.60276881  51.01906074 -27.24398461]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[ 0.99829583 -0.05255828  0.02535863]
 [ 0.05233779  0.9985863   0.00928176]
 [-0.02581062 -0.00793873  0.99963533]], [-52.62763516  -3.98062454 -25.97860386]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-2.59310451e-01  9.65793561e-01 -9.418

	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.25936867  0.96577726  0.00147377]
 [ 0.96435884  0.25890443  0.05459413]
 [ 0.0523442   0.01558125 -0.99850754]], [-51.99044482  -4.67371451 -27.00481047]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26801483  0.96339845  0.00560966]
 [ 0.96340063  0.26797479  0.00698095]
 [ 0.00522219  0.00727535 -0.9999599 ]], [-66.63093647  50.75954835 -26.42588041]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[ 0.99837122 -0.05251343  0.02229923]
 [ 0.05238098  0.99860613  0.00648321]
 [-0.0226086  -0.00530459  0.99973032]], [-52.12281883  -3.76216865 -26.0138352 ]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26812792  0.96337875  0.00296677]
 [ 0.96337501  0.26811154  0.00497971]
 [ 0.00400192  0.00419331 -0.9999832 ]], [-66.73917343  51.01684915 -26.50320176]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26593979  0.96398685  0.00232167]
 

	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-2.63891973e-01  9.64552039e-01 -6.24632697e-04]
 [ 9.64529059e-01  2.63890065e-01  6.76220888e-03]
 [ 6.68733672e-03  1.18201625e-03 -9.99976941e-01]], [-66.5681588   51.02014755 -26.69140889]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26435091  0.96442505  0.00170987]
 [ 0.96440718  0.26433393  0.00680965]
 [ 0.00611542  0.00344915 -0.99997535]], [-66.74259875  51.1038973  -26.6028383 ]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-2.59861308e-01  9.65645948e-01 -6.59958628e-05]
 [ 9.65626828e-01  2.59856591e-01  6.27546831e-03]
 [ 6.07703001e-03  1.56702403e-03 -9.99980307e-01]], [-66.58380558  51.09063858 -26.64164719]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26060552  0.96544353  0.00188559]
 [ 0.96543691  0.26059456  0.00469504]
 [ 0.00404142  0.00304397 -0.9999872 ]], [-66.4816471   50.90135904 -26.5844793 ]
	Aligning 955 atoms agianst 955 

	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-2.66650219e-01  9.63792852e-01  9.99627244e-04]
 [ 9.63764314e-01  2.66633983e-01  8.04155785e-03]
 [ 7.48386138e-03  3.10768823e-03 -9.99967167e-01]], [-66.83580428  51.12161379 -26.66445647]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.27541846  0.96121701 -0.01437148]
 [ 0.96114985  0.27562257  0.01493862]
 [ 0.01832036 -0.00969877 -0.99978513]], [-66.64802216  50.59378636 -26.85328404]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26353233  0.96464716  0.00256253]
 [ 0.96462689  0.26350632  0.0077065 ]
 [ 0.00675881  0.00450279 -0.99996702]], [-66.81076031  51.16753424 -26.56700219]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.2654286   0.96412881  0.00181495]
 [ 0.96411068  0.2654106   0.00691406]
 [ 0.00618433  0.003585   -0.99997445]], [-66.76590268  51.09739795 -26.59068311]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-2

	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.25982221  0.9656555   0.00136615]
 [ 0.96565148  0.25981606  0.00358223]
 [ 0.00310425  0.00224997 -0.99999265]], [-66.52580064  51.05090117 -26.61981425]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-2.58217963e-01  9.66080473e-01 -3.46447793e-03]
 [ 9.66022587e-01  2.58240479e-01  1.05932001e-02]
 [ 1.11285522e-02 -6.11409379e-04 -9.99937889e-01]], [-66.40049625  50.98135689 -26.91018703]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26172925  0.96513793  0.00256419]
 [ 0.96512957  0.26171201  0.00563432]
 [ 0.00476681  0.00394944 -0.99998084]], [-66.78503568  51.22241161 -26.56462265]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-2.63960442e-01  9.64533187e-01  7.85405044e-04]
 [ 9.64521660e-01  2.63953077e-01  5.17108533e-03]
 [ 4.78037333e-03  2.12250215e-03 -9.99986321e-01]], [-66.69134933  51.05537868 -26.64858013]
	Aligning 955 atoms agianst 955 

	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26181098  0.9651171   0.00199698]
 [ 0.96509668  0.26179019  0.00736905]
 [ 0.00658921  0.00385658 -0.99997085]], [-66.66654851  51.06771876 -26.61119987]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-2.57800534e-01  9.66198009e-01  5.40684279e-04]
 [ 9.66175219e-01  2.57790517e-01  7.03537835e-03]
 [ 6.65818527e-03  2.33612005e-03 -9.99975105e-01]], [-66.60139677  51.10269928 -26.70587763]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-2.59168163e-01  9.65832065e-01  5.33694529e-04]
 [ 9.65814173e-01  2.59159905e-01  6.25509935e-03]
 [ 5.90306330e-03  2.13657234e-03 -9.99980294e-01]], [-66.53144563  50.98580482 -26.66302212]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26176723  0.96512835  0.00227867]
 [ 0.96510208  0.26174036  0.00836485]
 [ 0.00747674  0.00438879 -0.99996242]], [-66.70985957  51.07212632 -26.59932183]
	Aligning 955 atoms agianst 955 

	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.27214059  0.96225696  0.00101825]
 [ 0.96224477  0.27213139  0.00543236]
 [ 0.00495023  0.00245817 -0.99998473]], [-66.90774328  51.06647444 -26.6000374 ]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26624811  0.96390333  0.00151953]
 [ 0.96388082  0.26623017  0.00743386]
 [ 0.00676098  0.0034439  -0.99997121]], [-66.74934678  51.00553505 -26.61026383]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-2.60413435e-01  9.65496969e-01  6.68488018e-04]
 [ 9.65481918e-01  2.60405355e-01  5.80663575e-03]
 [ 5.43221135e-03  2.15753905e-03 -9.99982918e-01]], [-66.61415203  51.09726518 -26.62261867]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.25994398  0.96562019  0.00260128]
 [ 0.96560592  0.25992191  0.00676853]
 [ 0.0058597   0.00427126 -0.99997371]], [-66.73836764  51.15341364 -26.56917603]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0

	The alignment matrix is: [[-0.26011149  0.96557396  0.00298923]
 [ 0.96556717  0.26009211  0.00566817]
 [ 0.00469557  0.00436066 -0.99997947]], [-66.90332041  51.2680317  -26.5966373 ]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26124038  0.96527259  0.00151315]
 [ 0.96524911  0.26122218  0.0075578 ]
 [ 0.00690007  0.00343497 -0.99997029]], [-66.70334942  51.0821087  -26.63002781]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26345552  0.96466823  0.00252794]
 [ 0.96464548  0.26342823  0.00804193]
 [ 0.00709187  0.00455726 -0.99996447]], [-66.74226612  51.05512675 -26.59844788]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26559007  0.96408434  0.00181785]
 [ 0.96405693  0.26556692  0.00827296]
 [ 0.00749307  0.00394972 -0.99996413]], [-66.94625531  51.17788354 -26.64860811]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26584173  0.96401288  0.00271044]
 [ 0.9639873   0.26581062  0.00855531]


	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.25999386  0.96560494  0.00320818]
 [ 0.96560254  0.25997704  0.00486618]
 [ 0.00386475  0.004363   -0.99998301]], [-66.98154057  51.33962634 -26.64492698]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26090823  0.9653579   0.00332063]
 [ 0.96534821  0.2608831   0.00654467]
 [ 0.00545165  0.00491312 -0.99997307]], [-66.8581168   51.18049828 -26.54777256]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26362887  0.96461054  0.00513032]
 [ 0.96459022  0.26357123  0.00979356]
 [ 0.00809476  0.00753052 -0.99993888]], [-66.98952095  51.23500088 -26.51893309]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26808954  0.96338571  0.00399558]
 [ 0.96336357  0.2680458   0.00905981]
 [ 0.00765709  0.00627804 -0.99995098]], [-67.09538719  51.32275564 -26.64453377]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-2.59356738e-01  9.65781553e-01 -2.743

	The alignment matrix is: [[-0.26531716  0.96415658  0.00298381]
 [ 0.96413172  0.26528358  0.00863968]
 [ 0.00753845  0.00516904 -0.99995823]], [-66.8420254   51.12631659 -26.55857982]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.25873837  0.9659343   0.00503786]
 [ 0.9659355   0.25870573  0.00632109]
 [ 0.00480244  0.00650176 -0.99996733]], [-66.83639268  51.23789359 -26.51537571]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26598641  0.96396332  0.00509437]
 [ 0.96393769  0.26592432  0.01041054]
 [ 0.00868066  0.00767972 -0.99993283]], [-66.9819113   51.22428774 -26.54043653]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26338479  0.96468076  0.00441329]
 [ 0.96465802  0.26333531  0.00945647]
 [ 0.0079603   0.00674801 -0.99994555]], [-66.98847961  51.27602861 -26.53590593]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.2638522   0.96456031  0.00233048]
 [ 0.96455102  0.26383602  0.00564672]


	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[ 0.98812115 -0.1454359   0.04964861]
 [ 0.14461514  0.98929064  0.01976078]
 [-0.05199084 -0.0123461   0.99857124]], [-65.74671294  51.78693102 -27.17139865]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26254459  0.96491173  0.00396082]
 [ 0.96489327  0.26250468  0.00850087]
 [ 0.00716286  0.00605362 -0.99995602]], [-67.00632537  51.30274564 -26.56001238]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.2597808   0.96566484  0.00231517]
 [ 0.96565555  0.25976482  0.0056215 ]
 [ 0.00482708  0.00369602 -0.99998152]], [-66.78977443  51.20256509 -26.6020569 ]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26626552  0.96389309  0.00357641]
 [ 0.96387606  0.26623116  0.00799411]
 [ 0.00675331  0.00557578 -0.99996165]], [-66.94000409  51.20875378 -26.59653445]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26433251  0.96442279  0.00412322]
 

	The alignment matrix is: [[-0.26279931  0.96483882  0.00475193]
 [ 0.96482472  0.26275307  0.00860756]
 [ 0.00705633  0.00684684 -0.99995166]], [-66.97479631  51.27411419 -26.53233478]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.28289212  0.95902245 -0.0157477 ]
 [ 0.95852614  0.28326239  0.03146516]
 [ 0.03463652 -0.00619333 -0.99938079]], [-52.75510242  -6.2960108  -25.31865836]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26171207  0.96512931  0.00567606]
 [ 0.96511066  0.26164764  0.01009565]
 [ 0.00825848  0.00812018 -0.99993293]], [-67.04944396  51.38362068 -26.57244542]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26550813  0.96410173  0.0036439 ]
 [ 0.96407494  0.26546537  0.00936177]
 [ 0.00805837  0.00599861 -0.99994954]], [-67.14761726  51.4123302  -26.64177717]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26328946  0.96469477  0.00653126]
 [ 0.96468442  0.26321903  0.00998512]


	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26099636  0.96533775  0.00198181]
 [ 0.9653088   0.26097098  0.00854757]
 [ 0.0077341   0.00414394 -0.99996151]], [-66.82048242  51.26534434 -26.67168681]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26137577  0.96523533  0.00186442]
 [ 0.96520526  0.26135095  0.00863045]
 [ 0.00784315  0.00405534 -0.99996102]], [-66.92602278  51.29000056 -26.65100992]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26138384  0.96523219  0.0023052 ]
 [ 0.9651984   0.26135243  0.00932466]
 [ 0.00839799  0.00466229 -0.99995387]], [-66.8198679   51.16272205 -26.60161465]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26212038  0.96503277  0.00215772]
 [ 0.96500988  0.26209666  0.00782765]
 [ 0.00698841  0.00413401 -0.99996704]], [-66.98525349  51.32447353 -26.6505389 ]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26011595  0.9655762   0.00151682]
 

	The alignment matrix is: [[-0.26195133  0.9650796   0.00169361]
 [ 0.96504289  0.26192495  0.00935636]
 [ 0.00858603  0.00408532 -0.99995479]], [-66.95611094  51.31775169 -26.68716882]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26005713  0.96559181  0.00165931]
 [ 0.96556971  0.26003842  0.00742621]
 [ 0.0067392   0.00353342 -0.99997105]], [-66.89894292  51.33654894 -26.65290852]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26166391  0.96515502  0.00278967]
 [ 0.9651263   0.26163012  0.00899493]
 [ 0.00795164  0.00504603 -0.99995565]], [-66.89199859  51.24580064 -26.60135081]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26086227  0.96537493  0.00145374]
 [ 0.96534508  0.26084155  0.00839984]
 [ 0.0077298   0.00359456 -0.99996366]], [-66.8545195   51.28797977 -26.67629672]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26050598  0.96546258  0.00431714]
 [ 0.96546222  0.26048031  0.00571956]


	The alignment matrix is: [[-0.25948551  0.96574258  0.00292395]
 [ 0.96573379  0.25946494  0.00601541]
 [ 0.00505068  0.00438467 -0.99997763]], [-66.8885096   51.29516337 -26.59835117]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26330601  0.96469584  0.00564659]
 [ 0.9646777   0.26324243  0.01001782]
 [ 0.00817773  0.00808489 -0.99993388]], [-66.97923403  51.25735163 -26.4893242 ]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.25888827  0.96590511  0.00204296]
 [ 0.96589687  0.25887509  0.00518839]
 [ 0.00448262  0.00331651 -0.99998445]], [-66.7288337   51.15313456 -26.56761415]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26413703  0.96447838  0.00361712]
 [ 0.9644489   0.26409273  0.0096619 ]
 [ 0.00836343  0.00604059 -0.99994678]], [-67.00874775  51.27136278 -26.59433213]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26523597  0.96417676  0.00361355]
 [ 0.9641386   0.26518557  0.01064791]


	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26337903  0.96467226  0.00623918]
 [ 0.96466417  0.2633163   0.00935733]
 [ 0.00738388  0.00848324 -0.99993675]], [-67.05976044  51.33437837 -26.50156356]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26452719  0.96436719  0.00461446]
 [ 0.96434798  0.26447797  0.00918569]
 [ 0.00763796  0.00687981 -0.99994716]], [-66.96362588  51.22283582 -26.49370931]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26434289  0.96441818  0.0045177 ]
 [ 0.96440605  0.26430162  0.00810042]
 [ 0.00661815  0.00649818 -0.99995699]], [-66.91158514  51.1688024  -26.4958264 ]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26384956  0.96455485  0.00416544]
 [ 0.96453381  0.2638048   0.00903073]
 [ 0.00761177  0.00640046 -0.99995055]], [-66.94700032  51.21809144 -26.54312485]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26820088  0.96335159  0.00469095]
 

	The alignment matrix is: [[-0.26510645  0.96421096  0.00397392]
 [ 0.96418371  0.26505912  0.00966628]
 [ 0.00826701  0.00639418 -0.99994538]], [-67.10642354  51.36540444 -26.61743388]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26551675  0.96409747  0.00411343]
 [ 0.96406434  0.26546301  0.01045694]
 [ 0.00898954  0.0067421  -0.99993686]], [-66.94278324  51.22043891 -26.5760013 ]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26386554  0.96455253  0.0036587 ]
 [ 0.96452948  0.26382552  0.00888728]
 [ 0.00760699  0.00587397 -0.99995381]], [-66.87588202  51.17245707 -26.54690625]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26616173  0.96392138  0.00367592]
 [ 0.96389492  0.26611878  0.00934759]
 [ 0.00803211  0.00603117 -0.99994955]], [-66.93769688  51.18056091 -26.5899536 ]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26403956  0.96450124  0.00452447]
 [ 0.96447582  0.26398624  0.00988177]


	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.25852479  0.96599619  0.00403627]
 [ 0.96599597  0.25850252  0.0053137 ]
 [ 0.00408962  0.00527275 -0.99997774]], [-66.57727868  51.05745928 -26.49257849]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26309605  0.9647606   0.00417895]
 [ 0.96474428  0.26305525  0.00839124]
 [ 0.00699625  0.00623932 -0.99995606]], [-66.99474689  51.26262296 -26.5324073 ]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26452637  0.96436692  0.00471587]
 [ 0.96435251  0.26448023  0.00862782]
 [ 0.00707313  0.00683005 -0.99995166]], [-67.01592101  51.29312376 -26.51945568]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26395681  0.96452735  0.00371285]
 [ 0.96450805  0.26391911  0.00842197]
 [ 0.00714332  0.00580411 -0.99995764]], [-67.08509872  51.3778727  -26.67267886]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26538166  0.96413907  0.00290293]
 

	The alignment matrix is: [[-0.26874489  0.96319855  0.00497417]
 [ 0.96316421  0.26867702  0.01128554]
 [ 0.00953377  0.00782387 -0.99992394]], [-66.97802962  51.11089014 -26.5888233 ]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26412414  0.9644774   0.00466741]
 [ 0.96445908  0.26407501  0.00911467]
 [ 0.00755835  0.00690893 -0.99994757]], [-67.00020128  51.27882925 -26.51936512]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26457864  0.96435618  0.00391223]
 [ 0.96432511  0.26452928  0.01006695]
 [ 0.00867323  0.00643616 -0.99994167]], [-67.02640059  51.28021334 -26.59868303]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26572974  0.96403361  0.00518677]
 [ 0.96401126  0.2656692   0.01010748]
 [ 0.00836598  0.00768596 -0.99993547]], [-67.02755812  51.25272974 -26.53319233]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.2603088   0.96552123  0.00284283]
 [ 0.96547959  0.26026663  0.01050916]


	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26017657  0.9655556   0.00324637]
 [ 0.96553677  0.26014471  0.00796728]
 [ 0.00684833  0.00520739 -0.99996299]], [-66.83896751  51.23477846 -26.58110288]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26033598  0.96550649  0.0047322 ]
 [ 0.96549329  0.26029104  0.00844269]
 [ 0.00691972  0.00676685 -0.99995316]], [-66.96504319  51.32860964 -26.53977717]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.25985981  0.96563832  0.00393925]
 [ 0.96563228  0.25983183  0.0064587 ]
 [ 0.00521322  0.00548222 -0.99997138]], [-66.89513907  51.23599885 -26.51698133]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26854363  0.9632578   0.0043275 ]
 [ 0.96323117  0.26849175  0.00989445]
 [ 0.008369    0.00682548 -0.99994168]], [-66.90840218  51.10671247 -26.55176897]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26578065  0.96402702  0.00354134]
 

	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26453302  0.96436691  0.00432966]
 [ 0.96435285  0.2644923   0.00820994]
 [ 0.00677223  0.00634712 -0.99995692]], [-67.00873305  51.26257749 -26.5345264 ]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26303173  0.96478121  0.00339423]
 [ 0.96475822  0.26299495  0.00867326]
 [ 0.00747514  0.00555595 -0.99995663]], [-67.02261847  51.31784586 -26.59923422]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26544004  0.96411842  0.00415527]
 [ 0.96409815  0.26539597  0.00892964]
 [ 0.00750644  0.00637637 -0.9999515 ]], [-66.90368784  51.16243514 -26.52968088]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26256076  0.96491097  0.00294212]
 [ 0.96489601  0.26253489  0.00714924]
 [ 0.00612597  0.00471595 -0.99997012]], [-67.11319498  51.39141166 -26.56798095]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26816938  0.963367    0.00303277]
 

	The alignment matrix is: [[-0.26416377  0.96447054  0.00375268]
 [ 0.96445453  0.26412834  0.00797977]
 [ 0.00670507  0.00572726 -0.99996112]], [-66.95200167  51.20929317 -26.5538381 ]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26500349  0.96423344  0.00519888]
 [ 0.96421612  0.26494756  0.00948996]
 [ 0.00777311  0.00752772 -0.99994145]], [-66.91336796  51.16685971 -26.51393525]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26063145  0.96543372  0.00299737]
 [ 0.96542469  0.26060997  0.00613272]
 [ 0.00513959  0.00449211 -0.9999767 ]], [-66.88105879  51.32415184 -26.61931693]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26615334  0.96391917  0.00471534]
 [ 0.96389402  0.26609735  0.01002601]
 [ 0.00840952  0.00721354 -0.99993862]], [-67.07241884  51.27867477 -26.57581972]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26245428  0.96493656  0.00389792]
 [ 0.96490783  0.262407    0.00976958]


	The alignment matrix is: [[-0.26062403  0.96543233  0.00394024]
 [ 0.96541917  0.26058908  0.00769209]
 [ 0.00639941  0.00580873 -0.99996265]], [-66.87688433  51.24796253 -26.57593306]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26070598  0.96541596  0.00210152]
 [ 0.96540444  0.26068999  0.0059156 ]
 [ 0.00516317  0.00357105 -0.99998029]], [-66.79017329  51.29458475 -26.6069432 ]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26294636  0.96479663  0.00516518]
 [ 0.96478372  0.26289545  0.00885178]
 [ 0.00718226  0.00731082 -0.99994748]], [-67.01994469  51.29120661 -26.50648023]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26153246  0.96518188  0.00497132]
 [ 0.9651659   0.26148141  0.00906911]
 [ 0.00745343  0.00717002 -0.99994652]], [-67.0132397   51.35176048 -26.55491526]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26447115  0.9643823   0.00466846]
 [ 0.96435258  0.26441216  0.01050287]


	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26219148  0.96500516  0.00454678]
 [ 0.9649934   0.26215031  0.00805869]
 [ 0.00658474  0.00650054 -0.99995719]], [-66.98144563  51.2583018  -26.51382467]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26208732  0.96503312  0.00461661]
 [ 0.96502052  0.26204442  0.00825325]
 [ 0.0067549   0.0066182  -0.99995528]], [-67.02030949  51.34421705 -26.52490258]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26303598  0.96478396  0.00199758]
 [ 0.96475906  0.26301258  0.0080207 ]
 [ 0.00721286  0.00403691 -0.99996584]], [-67.08081445  51.47460212 -26.67616004]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26201577  0.96505378  0.00435209]
 [ 0.96504227  0.26197734  0.0078293 ]
 [ 0.00641555  0.00625135 -0.99995988]], [-66.98360652  51.35435902 -26.53147096]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26044695  0.96547805  0.00441881]
 

	The alignment matrix is: [[-0.262198    0.96501036  0.00268448]
 [ 0.96499629  0.26217524  0.00680474]
 [ 0.00586284  0.00437471 -0.99997324]], [-67.00237583  51.33259422 -26.586309  ]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26324107  0.96471558  0.00529043]
 [ 0.9646984   0.26318401  0.00954861]
 [ 0.00781933  0.00761725 -0.99994042]], [-66.95079258  51.27225818 -26.50256526]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26413363  0.96447755  0.00405916]
 [ 0.9644526   0.26408704  0.00944591]
 [ 0.0080384   0.00640985 -0.99994715]], [-67.03461581  51.35004916 -26.55531117]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26577118  0.96403194  0.00284528]
 [ 0.96400496  0.26573769  0.00882725]
 [ 0.00775365  0.00508889 -0.99995699]], [-66.76164605  51.02946228 -26.59983994]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26040115  0.96549719  0.00253147]
 [ 0.96549474  0.26038963  0.0041411 ]


	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26458152  0.96434951  0.00516256]
 [ 0.96432782  0.26452205  0.00999745]
 [ 0.00827542  0.00762354 -0.9999367 ]], [-66.97373933  51.25503574 -26.52141748]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26319033  0.96473449  0.00426812]
 [ 0.96470678  0.2631388   0.00993955]
 [ 0.00846592  0.00673348 -0.99994149]], [-66.95685231  51.25688572 -26.53059061]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26588999  0.96399117  0.00485193]
 [ 0.96396506  0.26583117  0.01025438]
 [ 0.00859533  0.00740363 -0.99993565]], [-66.97102503  51.17707193 -26.53871048]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26331711  0.96470145  0.00389972]
 [ 0.96467678  0.26327286  0.00927989]
 [ 0.00792563  0.00620553 -0.99994934]], [-66.98859952  51.25420467 -26.54537971]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26963272  0.96295236  0.00457653]
 

	The alignment matrix is: [[-0.27049547  0.96270689  0.00525846]
 [ 0.9626679   0.27041895  0.01200424]
 [ 0.01013457  0.00830925 -0.99991412]], [-66.92234421  51.01369798 -26.54340997]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26576511  0.96401983  0.00588902]
 [ 0.96400314  0.26569878  0.01010479]
 [ 0.00817651  0.00836254 -0.9999316 ]], [-66.97083289  51.2010608  -26.50075226]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26534095  0.96413685  0.00585845]
 [ 0.96411568  0.2652707   0.0106024 ]
 [ 0.00866809  0.00846147 -0.99992663]], [-67.1928812   51.43023212 -26.60705667]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26562173  0.96406404  0.00506183]
 [ 0.9640235   0.26554776  0.01196119]
 [ 0.0101872   0.00805687 -0.99991565]], [-66.98029085  51.20203477 -26.54619391]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[ 0.99854049 -0.04830151  0.02416291]
 [ 0.04815126  0.99881717  0.00676203]


	The alignment matrix is: [[-0.26489893  0.96426551  0.00453797]
 [ 0.96423471  0.26484096  0.01052081]
 [ 0.00894301  0.00716262 -0.99993436]], [-66.9580145   51.19935594 -26.53443667]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.27075778  0.96264136  0.00343984]
 [ 0.96259647  0.2707049   0.01126427]
 [ 0.00991227  0.00636107 -0.99993064]], [-66.87497419  50.93576533 -26.57345341]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26124499  0.96527139  0.00148446]
 [ 0.96525157  0.26122887  0.00699162]
 [ 0.00636102  0.0032594  -0.99997446]], [-66.72120603  51.13878287 -26.61561836]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26309858  0.96476194  0.00367979]
 [ 0.96473644  0.26305648  0.00921304]
 [ 0.0079204   0.00597396 -0.99995079]], [-66.88611546  51.23421694 -26.55135176]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26619184  0.96391328  0.00361829]
 [ 0.963893    0.26615435  0.00849372]


	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26117005  0.96528086  0.00480232]
 [ 0.9652548   0.26111238  0.01017364]
 [ 0.00856648  0.00729251 -0.99993672]], [-67.05276979  51.44047898 -26.66355657]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26200263  0.96505221  0.00537131]
 [ 0.96503125  0.26194081  0.01008496]
 [ 0.00832554  0.00782576 -0.99993472]], [-67.03112708  51.5081311  -26.58509444]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26074993  0.96539806  0.00400628]
 [ 0.96538136  0.26071105  0.00828166]
 [ 0.00695062  0.00602703 -0.99995768]], [-67.00595256  51.34841626 -26.55844637]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.2585072   0.96600768  0.00178512]
 [ 0.96599991  0.25849608  0.00489425]
 [ 0.00426643  0.00298963 -0.99998643]], [-66.87381344  51.31652308 -26.63268949]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26077916  0.96533106  0.01140933]
 

	The alignment matrix is: [[-0.26195066  0.96506041  0.00634528]
 [ 0.96505431  0.26188853  0.0091965 ]
 [ 0.00721343  0.00853257 -0.99993758]], [-66.96642974  51.32648313 -26.48307098]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.262578    0.96490034  0.00448633]
 [ 0.96487893  0.26252872  0.00934457]
 [ 0.00783879  0.00678244 -0.99994627]], [-67.01098558  51.34031458 -26.53456038]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26220556  0.96500132  0.00454901]
 [ 0.96498011  0.26215562  0.00937112]
 [ 0.00785059  0.00684687 -0.99994574]], [-66.98822078  51.28868216 -26.54036041]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26498606  0.96424114  0.00462755]
 [ 0.96420509  0.26492259  0.01116112]
 [ 0.00953607  0.00741945 -0.999927  ]], [-66.999783    51.23723811 -26.56131945]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26209473  0.96503315  0.00416741]
 [ 0.96500131  0.26204146  0.010332  ]


	The alignment matrix is: [[-0.26311021  0.96475768  0.0039534 ]
 [ 0.96474785  0.26307812  0.00717592]
 [ 0.00588297  0.00570209 -0.99996644]], [-67.10078931  51.37398238 -26.57585445]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26251514  0.96491402  0.00517008]
 [ 0.9648983   0.26246138  0.00923605]
 [ 0.00755505  0.00741321 -0.99994398]], [-66.9890209   51.32380763 -26.52066738]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26157682  0.96517107  0.00473008]
 [ 0.96516675  0.26154123  0.00702372]
 [ 0.00554198  0.00640256 -0.99996415]], [-66.9178367   51.28873073 -26.50352702]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26125716  0.96525723  0.00481476]
 [ 0.96523647  0.26120394  0.00954227]
 [ 0.00795311  0.00714036 -0.99994288]], [-67.05221672  51.34883762 -26.58142124]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26277161  0.96483756  0.00629056]
 [ 0.96482488  0.26270292  0.01000639]


	The alignment matrix is: [[-0.26179048  0.9651087   0.00556282]
 [ 0.96509379  0.26173159  0.00951601]
 [ 0.00772802  0.00785984 -0.99993925]], [-66.96929391  51.27461562 -26.49597398]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26687823  0.96371265  0.00582589]
 [ 0.96367973  0.26679746  0.01185275]
 [ 0.00986831  0.00877754 -0.99991278]], [-66.98444237  51.16745347 -26.5537528 ]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26443432  0.96439587  0.0038853 ]
 [ 0.96436547  0.26438582  0.00996916]
 [ 0.008587    0.00638303 -0.99994276]], [-66.88000731  51.13379954 -26.5308406 ]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26313165  0.96474216  0.00585621]
 [ 0.96472092  0.26306157  0.01059063]
 [ 0.00867668  0.00843633 -0.99992677]], [-67.062315    51.34962928 -26.54635111]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26421826  0.96445543  0.00379931]
 [ 0.96442244  0.26416904  0.0102014 ]


	The alignment matrix is: [[-0.26548558  0.96410795  0.00364124]
 [ 0.96407187  0.2654362   0.01044233]
 [ 0.00910102  0.00628271 -0.99993885]], [-66.94408542  51.16449898 -26.53668268]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26369513  0.96459209  0.00519342]
 [ 0.9645663   0.26363155  0.0105006 ]
 [ 0.00875965  0.00777836 -0.99993138]], [-66.92620875  51.156794   -26.51293073]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26505266  0.9642121   0.00648921]
 [ 0.96419149  0.26497184  0.01116641]
 [ 0.00904733  0.00921653 -0.9999166 ]], [-66.97009712  51.23052366 -26.49781875]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26475909  0.96429645  0.00591413]
 [ 0.96428733  0.26470051  0.00914232]
 [ 0.00725043  0.00812344 -0.99994072]], [-66.97291586  51.22561983 -26.48106941]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26710355  0.96365115  0.0056702 ]
 [ 0.96362816  0.26703453  0.01064594]


	The alignment matrix is: [[-0.26304016  0.96477839  0.00354002]
 [ 0.96475174  0.26299894  0.00925384]
 [ 0.00799688  0.00584937 -0.99995092]], [-67.04574596  51.36173302 -26.60991794]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26517956  0.96419461  0.00292612]
 [ 0.9641539   0.26513655  0.01048157]
 [ 0.00933045  0.00560073 -0.99994079]], [-66.88134299  51.1378001  -26.57509363]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26153251  0.96517795  0.00568129]
 [ 0.96516455  0.26147332  0.00943871]
 [ 0.00762453  0.00795191 -0.99993931]], [-66.97818679  51.29586889 -26.4873941 ]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26539314  0.96412754  0.00495678]
 [ 0.96409411  0.26532662  0.01115035]
 [ 0.0094352   0.00773803 -0.99992555]], [-66.98301427  51.18286607 -26.53020928]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26775786  0.96347027  0.00554698]
 [ 0.9634284   0.26767427  0.01249821]


	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.25971131  0.96568472  0.00174807]
 [ 0.96567363  0.2596982   0.00559312]
 [ 0.00494722  0.00314066 -0.99998283]], [-66.85381104  51.29329839 -26.63859193]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26004506  0.96559564  0.00127674]
 [ 0.9655854   0.26003552  0.0051354 ]
 [ 0.00462672  0.00256823 -0.999986  ]], [-66.74685165  51.13739162 -26.6010219 ]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26404712  0.96450636  0.00256965]
 [ 0.96447329  0.26401301  0.00940209]
 [ 0.00838996  0.00496096 -0.9999525 ]], [-66.98903626  51.27388004 -26.63482413]
	Aligning 956 atoms agianst 956 atoms
	The alignment matrix is: [[-2.63071739e-01  9.64776154e-01  4.82092559e-04]
 [ 9.64731740e-01  2.63054761e-01  9.73968938e-03]
 [ 9.26980332e-03  3.02732701e-03 -9.99952452e-01]], [-66.7501795   51.07414967 -26.71442017]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0

	The alignment matrix is: [[-0.25910958  0.96584549  0.00217181]
 [ 0.96583923  0.25909704  0.0048277 ]
 [ 0.0041001   0.00334852 -0.99998599]], [-66.79628226  51.2721191  -26.60073636]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.25935868  0.96577127  0.00434996]
 [ 0.96576493  0.25932567  0.00694912]
 [ 0.0055832   0.00600335 -0.99996639]], [-66.8231435   51.24593703 -26.52173546]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-2.56231456e-01  9.66615436e-01  1.97869829e-04]
 [ 9.66607575e-01  2.56228535e-01  4.09074733e-03]
 [ 3.90347962e-03  1.23944062e-03 -9.99991613e-01]], [-66.67958135  51.17648462 -26.63782398]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.25769572  0.9662252   0.00133037]
 [ 0.96621761  0.25768743  0.00455174]
 [ 0.00405518  0.00245839 -0.99998876]], [-66.66400357  51.16530175 -26.62632494]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.25704814  0.96639447  0.00282394]
 [ 

	The alignment matrix is: [[-0.25925691  0.96580415  0.00286296]
 [ 0.96580038  0.25924154  0.00484233]
 [ 0.00393454  0.00402046 -0.99998418]], [-66.77326943  51.18204998 -26.52268427]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.25953154  0.96573137  0.00251166]
 [ 0.96572059  0.25951286  0.0060677 ]
 [ 0.00520796  0.00400032 -0.99997844]], [-66.75485773  51.17452419 -26.54689792]
	Aligning 956 atoms agianst 956 atoms
	The alignment matrix is: [[-0.26356067  0.96463564  0.00372111]
 [ 0.96461696  0.2635234   0.00833902]
 [ 0.00706352  0.00578729 -0.99995831]], [-66.95528508  51.23799952 -26.53776407]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-2.62169262e-01  9.65021903e-01 -6.21186320e-05]
 [ 9.65013680e-01  2.62167293e-01  4.11190752e-03]
 [ 3.98436630e-03  1.01807043e-03 -9.99991544e-01]], [-67.02157408  51.38225674 -26.73025168]
	Aligning 956 atoms agianst 956 atoms
	The alignment matrix is: [[-0.26269417  0.96487722  0.00192915]
 [ 

	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.25847691  0.96601649  0.00134977]
 [ 0.96600979  0.25846905  0.00433909]
 [ 0.00384276  0.00242544 -0.99998968]], [-66.77073199  51.2500324  -26.59545912]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.2606209   0.96543815  0.00243271]
 [ 0.96542903  0.26060411  0.00568266]
 [ 0.00485228  0.00382963 -0.99998089]], [-66.85002978  51.22361443 -26.601037  ]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26006922  0.96558753  0.00217287]
 [ 0.96557674  0.26005321  0.00582059]
 [ 0.00505522  0.00361183 -0.9999807 ]], [-66.74361261  51.12925265 -26.55930817]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-2.59549923e-01  9.65729361e-01  7.99826501e-04]
 [ 9.65721185e-01  2.59544072e-01  4.41216492e-03]
 [ 4.05336698e-03  1.91758646e-03 -9.99989946e-01]], [-66.85124236  51.28367721 -26.60928501]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0

	The alignment matrix is: [[-0.99961025  0.0234825  -0.01509721]
 [-0.02358719 -0.9996987   0.00679418]
 [-0.01493311  0.00714763  0.99986295]], [-67.26135733  49.87410282 -27.47865374]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26181593  0.96511164  0.00345689]
 [ 0.9651076   0.26179498  0.00554142]
 [ 0.00444309  0.00478711 -0.99997867]], [-66.7976699   51.14784244 -26.51309105]
	Aligning 956 atoms agianst 956 atoms
	The alignment matrix is: [[-0.26207937  0.96504542  0.00132283]
 [ 0.96503767  0.26207096  0.00459502]
 [ 0.00408773  0.00248084 -0.99998857]], [-66.75095131  51.13696009 -26.6229346 ]
	Aligning 956 atoms agianst 956 atoms
	The alignment matrix is: [[-0.26498196  0.96425228  0.00144725]
 [ 0.9642381   0.26496902  0.00602561]
 [ 0.00542673  0.00299217 -0.9999808 ]], [-66.99531654  51.28450012 -26.70826325]
	Aligning 956 atoms agianst 956 atoms
	The alignment matrix is: [[-0.26216015  0.96502325  0.00148014]
 [ 0.96501764  0.26215228  0.00414081]


	The alignment matrix is: [[-2.59772604e-01  9.65669594e-01  6.54674153e-04]
 [ 9.65653105e-01  2.59764060e-01  6.05925484e-03]
 [ 5.68117734e-03  2.20621654e-03 -9.99981428e-01]], [-66.70523526  51.19940319 -26.64362098]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26111823  0.96530285  0.00276991]
 [ 0.96530038  0.26110492  0.00440417]
 [ 0.00352813  0.0038238  -0.99998647]], [-66.83523417  51.22626774 -26.54188972]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26133103  0.96524527  0.00276936]
 [ 0.96523421  0.26130987  0.00632957]
 [ 0.00538593  0.00432719 -0.99997613]], [-66.79867919  51.15464209 -26.55185014]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.26078363  0.96539638  0.00131313]
 [ 0.965381    0.26077109  0.00616219]
 [ 0.00560653  0.00287467 -0.99998015]], [-67.04800542  51.46755861 -26.71951223]
	Aligning 955 atoms agianst 955 atoms
	The alignment matrix is: [[-0.2617728   0.9651269   0.0022524 ]
 [ 

	Aligning 964 atoms agianst 964 atoms
	The alignment matrix is: [[ 9.99998006e-01  5.72932581e-04  1.91293850e-03]
 [-5.83463208e-04  9.99984655e-01  5.50893578e-03]
 [-1.90975290e-03 -5.51004092e-03  9.99982996e-01]], [-0.15957153  0.15973068  0.04025687]
	Aligning 964 atoms agianst 964 atoms
	The alignment matrix is: [[ 9.99999083e-01 -1.23249376e-03 -5.61976176e-04]
 [ 1.23220867e-03  9.99999112e-01 -5.07371904e-04]
 [ 5.62601010e-04  5.06678966e-04  9.99999713e-01]], [-0.01361744 -0.03146485 -0.01892341]
	Aligning 964 atoms agianst 964 atoms
	The alignment matrix is: [[ 9.99997501e-01 -2.23221264e-03  1.25757719e-04]
 [ 2.23226630e-03  9.99997417e-01 -4.28140104e-04]
 [-1.24801695e-04  4.28419759e-04  9.99999900e-01]], [ 0.07302703 -0.06987906  0.01335274]
	Aligning 964 atoms agianst 964 atoms
	The alignment matrix is: [[ 9.99999272e-01 -9.81492585e-04 -7.01826361e-04]
 [ 9.81018021e-04  9.99999290e-01 -6.76208140e-04]
 [ 7.02489556e-04  6.75519144e-04  9.99999525e-01]], [ 0.001386

In [7]:
aligned_datasets._dictionary

{'MUREECA-x0083': <mdc3.types.datasets.Dataset at 0x7f92c339ada0>,
 'MUREECA-x0051': <mdc3.types.datasets.Dataset at 0x7f92c339add8>,
 'MUREECA-x0053': <mdc3.types.datasets.Dataset at 0x7f93414c20b8>,
 'MUREECA-x0054': <mdc3.types.datasets.Dataset at 0x7f93414c2390>,
 'MUREECA-x0059': <mdc3.types.datasets.Dataset at 0x7f93414c20f0>,
 'MUREECA-x0060': <mdc3.types.datasets.Dataset at 0x7f93414c24a8>,
 'MUREECA-x0061': <mdc3.types.datasets.Dataset at 0x7f93414c2470>,
 'MUREECA-x0062': <mdc3.types.datasets.Dataset at 0x7f93414c24e0>,
 'MUREECA-x0063': <mdc3.types.datasets.Dataset at 0x7f93414c2400>,
 'MUREECA-x0064': <mdc3.types.datasets.Dataset at 0x7f93414c21d0>,
 'MUREECA-x0065': <mdc3.types.datasets.Dataset at 0x7f93414c2208>,
 'MUREECA-x0066': <mdc3.types.datasets.Dataset at 0x7f93414c26a0>,
 'MUREECA-x0067': <mdc3.types.datasets.Dataset at 0x7f93414c26d8>,
 'MUREECA-x0070': <mdc3.types.datasets.Dataset at 0x7f93414c27b8>,
 'MUREECA-x0075': <mdc3.types.datasets.Dataset at 0x7f93414c22

In [12]:
# Cluster atom coords
def get_atom_coord_matrix(d, reference):
    ref_atom, common_set = mdc3.functions.alignment.common_set(reference.structure.structure, d.structure.structure)
    coords = [atom.coord for atom in common_set]
    array = np.array(coords).flatten()
    return array


atomic_matricies = aligned_datasets.bind(lambda d: get_atom_coord_matrix(d, reference_dataset))

In [13]:
np.vstack(atomic_matricies._dictionary.values())

/dls/science/groups/i04-1/conor_dev/anaconda/envs/env_clipper_no_mkl/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  """Entry point for launching an IPython kernel.


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2865 and the array at index 614 has size 2868

In [ ]:
# Plot
